server:
  port: 8003

spring:
  application:
    name: app-consumer

eureka:
  client:
    #是否将自己注册到EurrkeServer，默认为true
    register-with-eureka: true
    #表示是否从EurekaServer获取注册信息，默认为true，表示需要从其他server同步信息
    fetch-registry: true
    service-url:
      #设置与EurekaServer 交互的地址，查询服务和注册服务都依赖这个地址
      defaultZone: http://localhost:8000/eureka/

